### PR TITLE
Adding option to use previous settings file.

### PR DESCRIPTION
**Pull request by DaveKlassen4**
Created the changes required to load a learned settings file from cache, and potentially skip training altogether (if already completed). Open to suggestions on what I have done, but have tested the changes for how I am using the code.

### CODE REVIEW

**Comment by fgregg** [comment]
Thanks!

**Comment by fgregg** [comment]
Actually, this looks very good, but much of this could be moved to csvhelpers so that it would work with csvlink as well.

**Comment by fgregg** [comment]
Would you mind making a new PR that does that?

**Comment by DaveKlassen4** [comment]
I will look into it.

**Comment by fgregg** [comment]
Thanks!

**Comment by DaveKlassen4** [comment]
Done.

**Pull request merged**
